# Generated by Django 6.0.2 on 2026-02-24 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloghome', '0003_alter_authors_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='vote',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=2000)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('vote', models.IntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bloghome.authors')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bloghome.posts')),
            ],
        ),
    ]
