# Generated by Django 6.0.2 on 2026-02-25 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bloghome', '0004_posts_vote_comments'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comments',
            new_name='Comment',
        ),
    ]
