# Generated by Django 6.0.2 on 2026-02-26 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bloghome', '0006_remove_comment_author_remove_posts_author_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authormodel',
            name='password',
        ),
    ]
