# Generated by Django 6.0.2 on 2026-02-26 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bloghome', '0007_remove_authormodel_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authormodel',
            name='name',
        ),
    ]
