# Generated by Django 6.0.2 on 2026-03-05 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloghome', '0009_alter_postmodel_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='commentvotemodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='commentvotemodel',
            name='vote_type',
            field=models.CharField(choices=[('upvote', 'Upvote'), ('downvote', 'Downvote')], max_length=10),
        ),
        migrations.AlterField(
            model_name='postvotemodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='postvotemodel',
            name='vote_type',
            field=models.CharField(choices=[('upvote', 'Upvote'), ('downvote', 'Downvote')], max_length=10),
        ),
    ]
