# Generated by Django 6.0.2 on 2026-03-07 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bloghome', '0010_postmodel_points_alter_commentvotemodel_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postmodel',
            name='points',
        ),
    ]
